/**
 * Dev-only mock data for testing create + graphics flow.
 * Loaded dynamically only when "Fill mock (dev)" is clicked.
 */
import { SurveyData } from "../../types/quinipolo";

export const MOCK_SURVEY_DATA: SurveyData[] = [
  {
    gameType: "waterpolo",
    homeTeam: "CN Catalunya",
    awayTeam: "UE Horta",
    date: new Date(),
    isGame15: false,
    leagueId: "DHF",
  },
  {
    gameType: "waterpolo",
    homeTeam: "CN Mataró",
    awayTeam: "CN Sant Feliu",
    date: new Date(),
    isGame15: false,
    leagueId: "DHF",
  },
  {
    gameType: "waterpolo",
    homeTeam: "CN Caballa Ceuta",
    awayTeam: "CN Terrassa",
    date: new Date(),
    isGame15: false,
    leagueId: "DHM",
  },
  {
    gameType: "waterpolo",
    homeTeam: "CN Sabadell",
    awayTeam: "CN Barcelona",
    date: new Date(),
    isGame15: false,
    leagueId: "DHM",
  },
  {
    gameType: "waterpolo",
    homeTeam: "CN Sant Andreu",
    awayTeam: "CN Catalunya",
    date: new Date(),
    isGame15: false,
    leagueId: "DHM",
  },
  {
    gameType: "waterpolo",
    homeTeam: "Waterpolo Tenerife Echeyde",
    awayTeam: "CN Rubí",
    date: new Date(),
    isGame15: false,
    leagueId: "DHM",
  },
  {
    gameType: "waterpolo",
    homeTeam: "UVSE Margitsziget",
    awayTeam: "Olympiacos",
    date: new Date(),
    isGame15: false,
    leagueId: "CLF",
  },
  {
    gameType: "waterpolo",
    homeTeam: "CN Terrassa",
    awayTeam: "CN Mediterrani",
    date: new Date(),
    isGame15: false,
    leagueId: "DHF",
  },
  {
    gameType: "waterpolo",
    homeTeam: "CN Atlètic-Barceloneta",
    awayTeam: "CN Joventut",
    date: new Date(),
    isGame15: false,
    leagueId: "PDM",
  },
  {
    gameType: "waterpolo",
    homeTeam: "CN Sabadell",
    awayTeam: "CN Sant Andreu",
    date: new Date(),
    isGame15: false,
    leagueId: "PDM",
  },
  {
    gameType: "waterpolo",
    homeTeam: "CN Rubí",
    awayTeam: "CN Catalunya",
    date: new Date(),
    isGame15: false,
    leagueId: "PDM",
  },
  {
    gameType: "waterpolo",
    homeTeam: "Club Waterpolo Pontevedra",
    awayTeam: "CN Joventut",
    date: new Date(),
    isGame15: false,
    leagueId: "PDF",
  },
  {
    gameType: "waterpolo",
    homeTeam: "CN Rubí",
    awayTeam: "CN Catalunya",
    date: new Date(),
    isGame15: false,
    leagueId: "PDF",
  },
  {
    gameType: "waterpolo",
    homeTeam: "Boadilla",
    awayTeam: "Málaga",
    date: new Date(),
    isGame15: false,
    leagueId: "PDF",
  },
  {
    gameType: "waterpolo",
    homeTeam: "CN Sant Feliu",
    awayTeam: "UE Horta",
    date: new Date(),
    isGame15: true,
    leagueId: "PLENO_15",
    goalsHomeTeam: "11/12",
    goalsAwayTeam: "-",
  },
];
